 Parameters:

  projectName:
    Description: Name of the project
    Type: String
    Default: DefaultProject
 
 Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${projectName}-838894772923"
      #Public read access needed to S3 bucket as per requirements
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256      
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'